### ISSUE TITLE
rust contains many references to deprecated rumpbake

### ISSUE THREAD

**Issue by anttikantee** [rumpkernel/rumprun-packages#79]
Do rumpbake -> rumprun-bake where sanely possible.

**Comment by gandro** [comment]
While trying to update Rust (which needs another upstream fix I'm currently working on) I started considering dropping `cargo rumpbake` (which is the only remaining reference to rumpbake). 

All the tool does is calling `cargo build --target=x86_64-rumprun-netbsd` and then `rumprun-bake hw_generic foo.img target/x86_64-rumprun-netbsd/debug/foo` on the generated Rust binary. It sounded like a fun idea at the time, but considering the new config directives for rumprun-bake I don't think "build & bake" should actually be provided as a single command.

Also, it adds ~5-15 minutes to the build time of the package (since it needs to build cargo and all dependencies again) and uses two currently unstable APIs (rumprun-bake and cargo's internal API), thus adding a maintenance burden as well.

If there are no objections, I'd like to remove `cargo rumpbake` from the Makefile when I update the Rust package in a few days.

**Comment by anttikantee** [comment]
Yes, there's a reason why we split build and bake in the "upstream" tooling ;-)
(so no objections from me)
